version: "3"

services:
  todo-db:
    image: postgres:15.3
    container_name: todo-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_app
    volumes:
      - ./postgres:/var/lib/postgresql/data
